receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name, deployment.environment

exporters:

  otlp/tempo:
    endpoint: http://observex.duckdns.org:4317
    tls:
      insecure: true

  loki:
    endpoint: http://observex.duckdns.org:3100/loki/api/v1/push

  prometheusremotewrite:
    endpoint: http://observex.duckdns.org:9090/api/v1/write

  logging:
    verbosity: normal

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]

    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [loki]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
